"A customer, who is able to able make payments."
type Customer implements Identifiable {
  "The ID - this should be a unique string, or a structured ID (to be defined)."
  id: ID!
  "Full name of a customer."
  fullName: String!
  "Email of the customer."
  emailAddress: String!
  "Payments made by a customer."
  paymentsConnection(
    first: Int
    after: String
    last: Int
    before: String
  ): CustomerPaymentsConnection
}

"Connection between Customer and payments"
type CustomerPaymentsConnection {
  pageInfo: CustomerPaymentsPageInfo!
  edges: [CustomerPaymentsEdge]
}

"Edge between Customer and payments"
type CustomerPaymentsEdge {
  cursor: String!
  node: Payment
}

"Page info for connection between Customer and payments"
type CustomerPaymentsPageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
}
