"A payment envelope representing a customer's issued payment to a system"
type Payment implements Identifiable {
  "The ID - this should be a unique string, or a structured ID (to be defined)."
  id: ID!

  "Free text representing details on the payment."
  details: String!

  "Customer who made the payment is for."
  madeBy: Customer!

  "Invoice associated with the payment."
  invoice: Invoice!
}
