"Represents a connection between two entities."
interface Relationship {
  "The type of relationship."
  type: RelationshipType!
  "The nodes which the current entity is being related to."
  entities: [Identifiable]!
}
