"Represents a connection between two entities."
type Relationship {
  "The type of relationship."
  type: RelationshipType!

  "The nodes which the current entity is being related to."
  entities: [Identifiable]!
}
